# Generated by Django 3.0.7 on 2020-06-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='raiting',
            field=models.PositiveIntegerField(default=0, verbose_name='Plus'),
        ),
    ]
